const box = null;
console.log(box);
let box1 = 5;
console.log(box1);
let box2 = "2";
console.log(box2);
let result = box1 + box2;
console.log(result);
result = box2 - box1;
console.log(result);
result = box + box1;
console.log(result);
